# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: tabia

before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0

builds:
  - id: binary
    dir: cmd/tabia
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 8
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: archive
    format: tar.gz
    files:
      - LICENSE*
      - README*
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/philips-labs/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Major }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=com.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
    extra_files:
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "lib"
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  prerelease: auto
