// Code generated by "stringer -type=Visibility"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Public-0]
	_ = x[Internal-1]
	_ = x[Private-2]
}

const _Visibility_name = "PublicInternalPrivate"

var _Visibility_index = [...]uint8{0, 6, 14, 21}

func (i Visibility) String() string {
	if i < 0 || i >= Visibility(len(_Visibility_index)-1) {
		return "Visibility(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Visibility_name[_Visibility_index[i]:_Visibility_index[i+1]]
}
